name: evilog
channels:
  - conda-forge
dependencies:
  - cmake=3.19.6
  - configargparse=1.4
  - cudatoolkit=11.2
  - cudnn=8.1
  - matplotlib=3.3.4
  - numpy=1.19.5
  - opencv=4.4.0
  - pip=21.2.2
  - pyntcloud=0.1.4
  - python=3.8.11
  - scikit-image=0.17.2
  - tqdm=4.59.0
  - pip:
    - tensorflow==2.6.0
    - tensorflow-addons==0.14.0
    - git+https://github.com/ika-rwth-aachen/PointPillars.git

